### ISSUE TITLE
Tutorial in Pillar

### ISSUE THREAD

**Issue by gcotelli** [gcotelli/RenoirSt#50]
- Convert the online tutorial to Pillar markup and merge with the Pharo for Enterprise chapter
- Export markdown for this repo
- PDF and HTML for the Pharo for Enterprise chapter

**Comment by DamienCassou** [comment]
I'm working on it right now: https://github.com/SquareBracketAssociates/EnterprisePharo

**Comment by gcotelli** [comment]
Great! Please ask me any clarification you need.
