### ISSUE TITLE
CssAttributeReference requires quoting inside string

### ISSUE THREAD

**Issue by DamienCassou** [gcotelli/RenoirSt#53]
I find the following expression strange:

```smalltalk
CssAttributeReference
      toAttributeNamed: 'title'
      ofType: 'string'
      withFallback: '"Missing title"'
```

Why are the double-quotes inside the simple quotes necessary? What is the meaning of the expression if I remove the double-quotes?

**Comment by gcotelli** [comment]
The fallback could be of different types, for example: 

```smalltalk
CssAttributeReference
	toAttributeNamed: 'length'
	ofType: CssLengthUnits fontSize
        withFallback: 10 px.
```

If you remove the double quotes the final result would be:
`attr(title string, Missing title)` and that's invalid CSS. 

String implements cssContentOn: without the quotes (it's the usefull thing in the 99% of the cases). One main concern I have was that given the huge amount of concepts involved in CSS usually if something is missing as an abstraction you can just pass a String with the desired CSS result. 
For example:
```smalltalk
CssAttributeReference
	toAttributeNamed: 'length'
	ofType: CssLengthUnits fontSize
        withFallback: '10px'.
```
would be equivalent to the previous snippet, but that has the side effect of not quoting automatically the strings in the few cases is needed.

Maybe in that case we can add a new instance creation method like this:
```smalltalk
CssAttributeReference class>>
      toStringAttributeNamed: anAttributeName
      withFallback: aFallbackString

^self
      toAttributeNamed: anAttributeName
      ofType: 'string'
      withFallback: ('"<1s>"' expandMacrosWith: aFallbackString)
```
