### ISSUE TITLE
Support for Pharo 6

### ISSUE THREAD

**Issue by pierretsap** [gcotelli/RenoirSt#66]
Downloading RenoirSt from the catalog in Pharo 6 does nothing. That is strange, because there is not even an error saying it and it fails silently...

We have tested the installation instructions on Pharo6.1 and they work, tests are green. Maybe it makes sense to update the catalog configuration and to list Pharo6 as a supported platform?

We used

```
Metacello new
  baseline: 'RenoirSt';
  repository: 'github://gcotelli/RenoirSt:stable-pharo-50/source';
  load: #Development
```

**Comment by gcotelli** [comment]
Hi @pierretsap the development is moved to https://github.com/ba-st/RenoirSt/ . I will put a note on the README to redirect to the correct repo.

**Comment by pierretsap** [comment]
Ok, Thanks! So we will open there an issue to update the catalog :)

**Comment by gcotelli** [comment]
@pierretsap  Surelly the catalog configuration can be updated. But for us it is a mess... We're now using baselines and GitHub tags to mark the releases, and having to update each time the configuration and push it to the MetaRepos is impractical.
